# Generated by Django 5.2.7 on 2025-11-21 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the tenant', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name of the tenant organization', max_length=255)),
                ('slug', models.SlugField(help_text="URL-safe identifier for the tenant (e.g., 'acme-corp')", max_length=100, unique=True)),
                ('subdomain', models.CharField(db_index=True, help_text="Subdomain for this tenant (e.g., 'acme')", max_length=63, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active and can access the system')),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', help_text='Current subscription status', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='When the trial period ends', null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, help_text='When the current subscription period ends', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this tenant was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this tenant was last updated')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subdomain'], name='tenants_subdoma_69cf01_idx'), models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'), models.Index(fields=['is_active', 'subscription_status'], name='tenants_is_acti_a33816_idx')],
            },
        ),
    ]
