# Generated by Django 5.2.7 on 2025-11-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='language',
            field=models.CharField(default='en', help_text='Default language for the tenant', max_length=10),
        ),
    ]
