# Generated by Django 5.2.7 on 2025-11-21 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the group', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the group', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Description of the group's purpose and goals")),
                ('contribution_amount', models.DecimalField(decimal_places=2, help_text='Standard contribution amount per member per period', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('contribution_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', help_text='How often members should contribute', max_length=20)),
                ('currency', models.CharField(default='KES', help_text='Currency code (ISO 4217, e.g., KES, USD)', max_length=3)),
                ('allow_variable_contributions', models.BooleanField(default=False, help_text='Allow members to contribute amounts different from the standard')),
                ('require_contribution_approval', models.BooleanField(default=False, help_text='Require admin approval for contribution entries')),
                ('late_payment_grace_days', models.PositiveIntegerField(default=7, help_text='Number of days grace period before marking as defaulter')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this group was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this group was last updated')),
                ('tenant', models.ForeignKey(help_text='The tenant this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='groups_tenant__62f051_idx'), models.Index(fields=['created_at'], name='groups_created_d34ebd_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_group_name_per_tenant')],
            },
        ),
    ]
