# Generated by Django 5.2.7 on 2025-11-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.CharField(default='RWF', help_text='Currency code (ISO 4217, e.g., RWF, USD)', max_length=3),
        ),
    ]
