# Generated by Django 5.2.7 on 2025-11-21 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the contribution', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Contribution amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', help_text='Method of payment', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Payment reference number (e.g., M-Pesa code)', max_length=100)),
                ('contribution_date', models.DateField(help_text='Date when the contribution was made')),
                ('period_start', models.DateField(help_text='Start date of the contribution period')),
                ('period_end', models.DateField(help_text='End date of the contribution period')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Approval status of the contribution', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the contribution was approved', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this contribution')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this contribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contributions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='The group this contribution is for', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.group')),
                ('member', models.ForeignKey(help_text='The member who made the contribution', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this contribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'db_table': 'contributions',
                'ordering': ['-contribution_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the expense', primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Description of the expense', max_length=255)),
                ('category', models.CharField(choices=[('loan', 'Member Loan'), ('welfare', 'Welfare/Emergency'), ('administrative', 'Administrative'), ('investment', 'Investment'), ('event', 'Event/Meeting'), ('other', 'Other')], help_text='Category of expense', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField(help_text='Date when the expense occurred')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', help_text='Approval status of the expense', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the expense was approved', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the expense was paid', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this expense')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(blank=True, help_text='Member who received the funds (for loans, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_expenses', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='The group this expense is for', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group')),
                ('paid_by', models.ForeignKey(blank=True, help_text='User who marked this as paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='User who requested/recorded this expense', on_delete=django.db.models.deletion.CASCADE, related_name='requested_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the transaction', primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('contribution', 'Contribution'), ('expense', 'Expense'), ('adjustment', 'Adjustment')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (positive for contributions, negative for expenses)', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Group balance after this transaction', max_digits=12)),
                ('transaction_date', models.DateField(help_text='Date of the transaction')),
                ('description', models.CharField(help_text='Description of the transaction', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this transaction was recorded')),
                ('contribution', models.ForeignKey(blank=True, help_text='Related contribution if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financials.contribution')),
                ('created_by', models.ForeignKey(help_text='User who created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, help_text='Related expense if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financials.expense')),
                ('group', models.ForeignKey(help_text='The group this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='groups.group')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['group', 'contribution_date'], name='contributio_group_i_26c37a_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['member', 'contribution_date'], name='contributio_member__39ded1_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['status'], name='contributio_status_b92c24_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['period_start', 'period_end'], name='contributio_period__8a8056_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'expense_date'], name='expenses_group_i_8cd23b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='expenses_status_86293f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expenses_categor_a6f264_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['group', 'transaction_date'], name='transaction_group_i_fa4fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_ddda52_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-transaction_date', '-created_at'], name='transaction_transac_63c5c1_idx'),
        ),
    ]
