# Generated by Django 5.2.7 on 2025-11-21 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user profile', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for notifications', max_length=20)),
                ('timezone', models.CharField(default='Africa/Nairobi', help_text="User's timezone", max_length=50)),
                ('language', models.CharField(default='en', help_text='Preferred language code', max_length=10)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this profile was last updated')),
                ('user', models.OneToOneField(help_text='Associated Django user account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the invitation', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of the invitee', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('treasurer', 'Treasurer'), ('member', 'Member')], default='member', help_text='Role to assign when invitation is accepted', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', help_text='Current status of the invitation', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from the inviter')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for the invitation link', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was sent')),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
                ('group', models.ForeignKey(help_text='The group the invitation is for', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='groups.group')),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, help_text='User account if invitee already has one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Invitation',
                'verbose_name_plural': 'Group Invitations',
                'db_table': 'group_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='group_invit_email_1a7c7f_idx'), models.Index(fields=['token'], name='group_invit_token_58add1_idx'), models.Index(fields=['group', 'status'], name='group_invit_group_i_66b8d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the membership', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('treasurer', 'Treasurer'), ('member', 'Member')], default='member', help_text="User's role in the group", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined the group')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this membership was last updated')),
                ('group', models.ForeignKey(help_text='The group the user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(help_text='The user who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'db_table': 'group_memberships',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='group_membe_user_id_72052f_idx'), models.Index(fields=['group', 'is_active'], name='group_membe_group_i_740f30_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'group'), name='unique_user_per_group')],
            },
        ),
    ]
